'\" t
.\"     Title: less2scss
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-07-23
.\"    Manual: User Commands
.\"    Source: less2scss
.\"  Language: English
.\"
.TH "LESS2SCSS" "1" "2016\-07\-23" "less2scss" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
less2scss \- Converts Less files to Scss\&.
.SH "SYNOPSIS"
.HP \w'\fBless2scss\fR\ 'u
\fBless2scss\fR [\fB\-h\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
Run
\fBless2scss \-\-help\fR
for more options\&.
.SH "EXAMPLE"
.PP
.if n \{\
.RS 4
.\}
.nf
	less2scss input\&.less > output\&.scss
      
.fi
.if n \{\
.RE
.\}
.sp

